---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Blackbox exporter for external probing
  - job_name: 'blackbox'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://mtz1:9101/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.containers.internal:9115  # Blackbox exporter address

  # Node exporter for system metrics (if installed)
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'mtz1:9100'